version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: eventspace_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: eventspace_user
      POSTGRES_PASSWORD: eventspace_password
      POSTGRES_DB: eventspace_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventspace_user -d eventspace_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: